### ISSUE TITLE
Wrong repo URL and path name in the README

### ISSUE THREAD

**Issue by alessandro-newzoo** [mainnebula/ReadMe-Generator#4]
The installation instructions mention:

> ### Clone the repository:
> ```
> git clone https://github.com/mainnebula/readme-generator-cli
> cd readme-generator-cli
> ```

but the git command returns a "not found" error.

The correct command should be

```
git clone https://github.com/mainnebula/ReadMe-Generator
cd ReadMe-Generator
```

there are probably other places in the README where this needs to be addressed

**Comment by mainnebula** [comment]
nice find, fixing!!
